# Generated by Django 4.1.1 on 2024-10-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_orderline_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_lines',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='viewer.order'),
            preserve_default=False,
        ),
    ]
