# Generated by Django 4.1.1 on 2024-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_promocode_order_promo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='minimum_order_value',
            new_name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='start_date',
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
